services:
  web:
    build:
      context: .
      dockerfile: Containerfile
    env_file: .env
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.24.2.2

networks:
  default:
    driver: bridge
    driver_opts:
      isolate: "false"
    ipam:
      config:
        - subnet: 172.24.2.0/24
          gateway: 172.24.2.1
