services:
  web:
    build:
      context: ./src
      dockerfile: Containerfile
    domainname: web
    env_file: .env
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.24.3.2
    depends_on:
      - redis
      - client
  client:
    build:
      context: ./client
      dockerfile: Containerfile
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
    depends_on:
      - firefox
      - redis
    networks:
      default:
        ipv4_address: 172.24.3.3
  redis:
    image: redis
    domainname: redis
    networks:
      default:
        ipv4_address: 172.24.3.4
  firefox:
    image: selenium/standalone-firefox
    shm_size: "2gb"
    environment:
      - SE_START_VNC=false
      - SE_START_NO_VNC=false
    networks:
      default:
        ipv4_address: 172.24.3.5

networks:
  default:
    driver: bridge
    driver_opts:
      isolate: "false"
    ipam:
      config:
        - subnet: 172.24.3.0/24
          gateway: 172.24.3.1
