[project]
name = "03"
version = "0.1.0"
description = "Náměstí microblog challenge"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "sqlalchemy>=2.0.31",
    "flask-sqlalchemy>=3.1.1",
    "argon2-cffi>=23.1.0",
    "redis>=5.0.0",
    "rq>=1.16.2",
]
